# Generated by Django 4.1 on 2022-09-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='deparment',
            field=models.CharField(default='Engineering', max_length=50),
        ),
        migrations.AddField(
            model_name='teacher',
            name='number_of_subjects',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='teacher',
            name='qualification',
            field=models.CharField(default='MSC', max_length=50),
        ),
        migrations.AddField(
            model_name='teacher',
            name='specialization',
            field=models.CharField(default='Engineering', max_length=50),
        ),
    ]
