# Generated by Django 4.1 on 2022-09-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_teacher_deparment_teacher_number_of_subjects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='gender',
            field=models.CharField(default='Male', max_length=5),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='deparment',
            field=models.CharField(default='Department Of', max_length=50),
        ),
    ]
