# Generated by Django 4.1 on 2022-09-05 16:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_reviewmodel_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='stars',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
